site_name: ft_IaC Documentation
theme: bootstrap386
use_directory_urls: false
nav:
  - Home: index.md
  - Module:
    - module/project.md
    - module/network.md
    - module/database.md
    - module/autoscaling.md
    - module/loadbalancer.md
    - module/monitoring.md
  - About: about.md
